// BACKEND/models/practicePaymentModel.js
//
// WHAT:
// Stores one application-owned payment attempt.
//
// WHY:
// Stripe processes the payment, but our backend still needs its own record
// connecting the authenticated user, product, amount, Stripe PaymentIntent,
// and final payment status.
//
// HOW:
// The backend creates this record before creating the Stripe PaymentIntent.
// Stripe webhooks will later update the authoritative payment status.
//
// IMPORTANT:
// Never store card numbers, CVC values, Stripe secret keys, or PaymentIntent
// client secrets in MongoDB.

import mongoose from "mongoose";

const practicePaymentSchema = new mongoose.Schema(
  {
    // Internal payment identifier returned to the frontend.
    //
    // This is separate from MongoDB's document identifier and Stripe's
    // PaymentIntent identifier.
    paymentId: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
    },

    // Authenticated application user.
    //
    // User._id is a UUID string in this project, not a MongoDB ObjectId.
    user: {
      type: String,
      ref: "User",
      required: true,
      index: true,
    },

    userEmail: {
      type: String,
      required: true,
      trim: true,
      lowercase: true,
      maxlength: 120,
    },

    productCode: {
      type: String,
      required: true,
      trim: true,
      maxlength: 100,
      index: true,
    },

    productName: {
      type: String,
      required: true,
      trim: true,
      maxlength: 160,
    },

    // Always store money in the currency's smallest unit.
    //
    // $10.00 CAD is stored as 1000 cents.
    amount: {
      type: Number,
      required: true,
      min: 1,
    },

    currency: {
      type: String,
      required: true,
      lowercase: true,
      trim: true,
      minlength: 3,
      maxlength: 3,
    },

    stripeProductId: {
      type: String,
      required: true,
      trim: true,
    },

    stripePaymentIntentId: {
      type: String,
      default: null,
      unique: true,
      sparse: true,
      index: true,
    },

    // Generated by the frontend once for each purchase attempt.
    //
    // The same key must be reused when retrying the same request.
    idempotencyKey: {
      type: String,
      required: true,
      unique: true,
      index: true,
      trim: true,
      maxlength: 200,
    },

    status: {
      type: String,
      required: true,
      enum: [
        "created",
        "payment_intent_created",
        "requires_payment_method",
        "requires_confirmation",
        "requires_action",
        "processing",
        "succeeded",
        "failed",
        "cancelled",
        "refunded",
      ],
      default: "created",
      index: true,
    },

    webhookConfirmed: {
      type: Boolean,
      default: false,
    },

    failureCode: {
      type: String,
      default: null,
      maxlength: 200,
    },

    failureMessage: {
      type: String,
      default: null,
      maxlength: 500,
    },

    paidAt: {
      type: Date,
      default: null,
    },

    failedAt: {
      type: Date,
      default: null,
    },

    cancelledAt: {
      type: Date,
      default: null,
    },

    refundedAt: {
      type: Date,
      default: null,
    },
  },
  {
    timestamps: true,
    collection: "practicePayments",
  }
);

const PracticePayment =
  mongoose.models.PracticePayment ||
  mongoose.model("PracticePayment", practicePaymentSchema);

export default PracticePayment;
